export const EN: Record<string, string> = {
  'Telegram или e-mail для связи': 'Telegram or e-mail for updates',
  'VPN вашего города': 'VPN in your city',
  '{n} заказов': '{n} orders',
  '{n} отзывов': '{n} reviews',
  'Акция': 'Promotion',
  'Без вас': 'Without you',
  'Без комиссии': 'No fee',
  'Больше': 'More',
  'Возврат за 24 часа': '24-hour refund',
  'Все игры': 'All games',
  'Все услуги': 'All services',
  'Все': 'All',
  'Калибровка': 'Placements',
  'Другое': 'Other',
  'Вход с того же региона, что и вы': 'Logins come from your region',
  'Вы в пати, +30%': 'You are in the party, +30%',
  'Выберите игру': 'Pick a game',
  'Выберите текущий уровень и цель — цена и срок рассчитаются сразу.': 'Pick your current level and target. Price and time are calculated instantly.',
  'Выберите услугу': 'Pick a service',
  'Выбрать игру': 'Pick a game',
  'Выбрать уровень': 'Choose level',
  'Демо-заказ: статусы меняются автоматически, исполнитель вымышленный.': 'Demo order: statuses change automatically, the booster is fictional.',
  'Демо-проект для портфолио. Не связан с Valve, Riot Games, Rockstar Games и FACEIT. Изображения — официальные материалы правообладателей. Заказы и оплата не настоящие.':
    'Portfolio demo. Not affiliated with Valve, Riot Games, Rockstar Games or FACEIT. Images are official materials of their owners. Orders and payments are not real.',
  'Демо: оплата не проводится, заказ создаётся только в этом браузере.': 'Demo: no payment is taken, the order lives only in this browser.',
  'Для {game} в этой категории пока ничего нет.': 'Nothing for {game} in this category yet.',
  'Друзья в Steam не увидят, что кто-то играет': 'Steam friends will not see anyone playing',
  'Если не начали вовремя — вернём деньги': 'If we do not start on time, you get your money back',
  'Ещё для {game}': 'More for {game}',
  'Заказ': 'Order',
  'Заказ #{id} не найден в этом браузере.': 'Order #{id} was not found in this browser.',
  'Заказов пока нет. Выберите игру и услугу — оформление займёт минуту.': 'No orders yet. Pick a game and a service, checkout takes a minute.',
  'Закрыть': 'Close',
  'Играет исполнитель': 'A booster plays',
  'Игры': 'Games',
  'Исполнитель играет. После каждой сессии пришлём скриншот статистики в {c}.': 'The booster is playing. After every session we send a stats screenshot to {c}.',
  'Исполнитель начнёт': 'A booster starts',
  'Как это работает': 'How it works',
  'Картой': 'Card',
  'Категории': 'Categories',
  'Количество': 'Amount',
  'Меньше': 'Less',
  'Меню': 'Menu',
  'Мои заказы': 'My orders',
  'На главную': 'Home',
  'Навигация': 'Breadcrumbs',
  'Настройка заказа': 'Order setup',
  'Ничего не нашли. Попробуйте «FACEIT» или «Dota».': 'Nothing found. Try “FACEIT” or “Dota”.',
  'Нужный уровень': 'Target level',
  'Обучение': 'Coaching',
  'Обычно в течение 15 минут. Вы видите, кто играет, и можете написать ему в чат.': 'Usually within 15 minutes. You see who plays and can message them.',
  'Оплата замораживается до старта. Не начали за 24 часа — вернём деньги.': 'Payment is held until we start. No start within 24 hours means a refund.',
  'Оплатите заказ': 'Pay for the order',
  'Оплатить {sum}': 'Pay {sum}',
  'Опции': 'Options',
  'Отзывы': 'Reviews',
  'Отзывы по {game}': '{game} reviews',
  'Оформить': 'Checkout',
  'Оформить заказ': 'Place order',
  'Оформление заказа': 'Checkout',
  'Оффлайн-статус': 'Offline status',
  'Очистить демо-заказы': 'Clear demo orders',
  'Подбираем игрока под ваш ранг и регион. Обычно это занимает несколько минут.': 'Matching a player to your rank and region. Usually takes a few minutes.',
  'Подвал': 'Footer',
  'Поднимем FACEIT': 'Raise your FACEIT',
  'Поиск услуг': 'Search services',
  'Поиск: FACEIT, MMR, калибровка…': 'Search: FACEIT, MMR, placements…',
  'Показать для всех игр': 'Show for all games',
  'Прокачка': 'Boosting',
  'Разделы': 'Sections',
  'Рассчитать стоимость': 'Get a price',
  'Режим': 'Mode',
  'Рейтинг': 'Rating',
  'С вами': 'With you',
  'СБП': 'SBP',
  'СБП · Visa · Mastercard · Мир': 'SBP · Visa · Mastercard · Mir',
  'СБП или картой. Деньги замораживаются до старта работы.': 'SBP or card. The money is held until work starts.',
  'Связь': 'Contact',
  'Скриншот статистики после каждой сессии. Заказ закрывается, когда цель достигнута.': 'A stats screenshot after every session. The order closes when the goal is reached.',
  'Следите за прогрессом': 'Track progress',
  'Создаём заказ…': 'Creating order…',
  'Способ оплаты': 'Payment method',
  'Срок': 'Time',
  'Старт': 'Start',
  'Сумма': 'Total',
  'Такой услуги нет.': 'This service does not exist.',
  'Текущий ранг, цель и опции. Цена считается сразу, без «уточните у менеджера».': 'Current rank, target and options. The price is instant, no “ask a manager”.',
  'Текущий уровень': 'Current level',
  'Текущий ранг': 'Current rank',
  'Нужный ранг': 'Target rank',
  'Текущий рейтинг': 'Current rating',
  'Нужный рейтинг': 'Target rating',
  'Укажите, куда написать, когда исполнитель начнёт': 'Tell us where to message you when the booster starts',
  'Услуги': 'Services',
  'Услуги для {game}': '{game} services',
  'Цель достигнута. Смените пароль, если давали его для заказа.': 'Goal reached. Change your password if you shared it for the order.',
  'Цена от': 'From',
  'Частые вопросы': 'FAQ',
  'Что входит': 'What is included',
  'без бесконечного гринда': 'without the endless grind',
  'бесплатно': 'free',
  'до воскресенья': 'until Sunday',
  'до воскресенья, на любой уровень': 'until Sunday, any level',
  'за 15 минут': 'in 15 minutes',
  'на буст FACEIT': 'off FACEIT boosting',
  'от': 'from',
  'отзывов': 'reviews',
  'Ищем исполнителя': 'Finding a booster',
  'Исполнитель назначен': 'Booster assigned',
  'В работе': 'In progress',
  'Выполнено': 'Completed',
  'Могут ли забанить аккаунт?': 'Can my account get banned?',
  'Играем без читов и сторонних программ, с VPN вашего города. За всё время работы банов по нашей вине не было — но если такое случится, вернём полную стоимость.':
    'We play without cheats or third-party software, through a VPN in your city. We have never caused a ban, and if it ever happens you get a full refund.',
  'Нужно ли давать пароль?': 'Do I need to share my password?',
  'Для режима «Без вас» — да, на время заказа. Steam Guard можно подтверждать самому. В режиме «С вами» вы играете на своём аккаунте, пароль не нужен.':
    'For “Without you”, yes, for the duration of the order. You can confirm Steam Guard yourself. In “With you” mode you play on your own account, no password needed.',
  'Можно ли следить за процессом?': 'Can I watch the progress?',
  'Да. После каждой сессии исполнитель присылает скриншот статистики, а с опцией «Стрим процесса» вы смотрите игру в реальном времени.':
    'Yes. After every session the booster sends a stats screenshot, and with “Live stream” you watch the games in real time.',
  'Что если не дойдём до цели?': 'What if the goal is not reached?',
  'Заказ не закрывается, пока цель не достигнута. Если сроки сорвутся больше чем на два дня — вернём 20% стоимости.':
    'The order stays open until the goal is reached. If we are more than two days late, we refund 20% of the price.',
  '{n} уровень': 'Level {n}',
  '{n} услуг': '{n} services',
  'Акции': 'Offers',
  'Буст FACEIT': 'FACEIT boost',
  'Буст рейтинга, калибровка, обучение, прокачка и помощь в популярных онлайн-играх.': 'Rank boosting, placements, coaching, leveling and help in popular online games.',
  'Быстро:': 'Quick:',
  'Вместе с вами': 'Together with you',
  'Во что играем?': 'What do you play?',
  'Вперёд': 'Next',
  'Всё для': 'Everything',
  'Выбрать': 'Choose',
  'Готово. Если давали пароль от аккаунта — поменяйте его.': 'Done. If you shared your account password, change it now.',
  'Демо-заказ: статусы меняются сами, исполнитель вымышленный.': 'Demo order: statuses change on their own, the booster is fictional.',
  'Демо-магазин: оплата не списывается.': 'Demo store: nothing is charged.',
  'Демо: оплата не проводится, заказ хранится только в этом браузере.': 'Demo: no payment is taken, the order lives only in this browser.',
  'Для {game} в этом разделе пока ничего нет.': 'Nothing for {game} in this section yet.',
  'Играет на вашем аккаунте': 'Plays on your account',
  'Исполнитель': 'Booster',
  'Исполнитель играет. Прогресс обновится здесь после сессии, а уведомление придёт в {c}.': 'The booster is playing. Progress updates here after each session, and we will ping {c}.',
  'Итого': 'Total',
  'Как проходит заказ': 'How an order works',
  'Кто играет': 'Who plays',
  'Любой банк': 'Any bank',
  'Назад': 'Previous',
  'Найти игру или услугу': 'Find a game or service',
  'Настройте заказ': 'Set up your order',
  'Ничего не нашли. Попробуйте «FACEIT», «MMR» или «калибровка».': 'Nothing found. Try “FACEIT”, “MMR” or “placements”.',
  'Оставьте контакт для связи и выберите способ оплаты.': 'Leave a contact and pick a payment method.',
  'Оформите заказ': 'Place the order',
  'По QR-коду': 'Via QR code',
  'Победы': 'Wins',
  'Подберём игрока под вашу игру и ранг. Его ник появится в заказе.': 'We match a player to your game and rank. Their nickname shows in the order.',
  'Подбираем игрока под вашу игру и ранг. Обычно это занимает несколько минут.': 'Matching a player to your game and rank. Usually takes a few minutes.',
  'Популярное сейчас': 'Popular right now',
  'После каждой сессии в заказе обновляется рейтинг или счёт матчей.': 'After every session the order shows your new rating or match count.',
  'Разбор игры': 'Game review',
  'Ранг и рейтинг': 'Rank & rating',
  'Сейчас': 'Now',
  'Сейчас заказывают': 'Ordered right now',
  'Укажите, откуда и докуда, отметьте нужные опции — цена посчитается сразу.': 'Set where you are and where you want to be, tick the options, and the price appears instantly.',
  'Уровень': 'Level',
  'Цель': 'Target',
  'Что пишут игроки': 'What players say',
  'игровые услуги': 'gaming services',
  'твоей игры': 'for your game',
};
