// Interface copy, [ru, en]. Written per language, not translated word for word.

export const dict = {
  // ---- common ----
  sandbox: ['SANDBOX', 'SANDBOX'],
  sandbox_hint: ['Демо-режим: платежи, балансы и выплаты симулированы', 'Demo mode: payments, balances and payouts are simulated'],
  sandbox_strip: ['Демо-режим. Деньги ненастоящие, курсы реальные.', 'Demo mode. The money is simulated, the rates are real.'],
  lang_label: ['Язык', 'Language'],
  open_demo: ['Открыть демо', 'Open demo'],
  explore_product: ['Посмотреть продукт', 'Explore product'],
  back_to_site: ['О продукте', 'Product site'],
  optional: ['необязательно', 'optional'],
  copy: ['Копировать', 'Copy'],
  copied: ['Скопировано', 'Copied'],
  copy_link: ['Скопировать ссылку', 'Copy link'],
  open_pay_page: ['Открыть страницу оплаты', 'Open payment page'],
  close: ['Закрыть', 'Close'],
  cancel: ['Отмена', 'Cancel'],
  save: ['Сохранить', 'Save'],
  clear: ['Очистить', 'Clear'],
  today: ['Сегодня', 'Today'],
  today_short: ['Сег.', 'Today'],
  yesterday: ['Вчера', 'Yesterday'],
  yesterday_short: ['Вчера', 'Yest.'],
  vs_yesterday: ['к вчера', 'vs yesterday'],
  payments_forms: ['платёж|платежа|платежей', 'payment|payments'],
  unavailable_demo: ['Недоступно в демо', 'Not available in the demo'],
  new_payment: ['Новый платёж', 'New payment'],
  create_payment: ['Создать платёж', 'Create payment'],
  create_invoice: ['Создать счёт', 'Create invoice'],
  create_link: ['Создать ссылку', 'Create link'],
  refund_btn: ['Вернуть платёж', 'Issue refund'],
  rates_live: ['Курсы CoinGecko · {time}', 'CoinGecko rates · {time}'],
  rates_cached: ['Последние сохранённые курсы', 'Last saved rates'],
  rates_reference: ['Справочные курсы', 'Reference rates'],
  rate_live: ['реальный курс', 'live rate'],
  rate_cached: ['сохранённый курс', 'saved rate'],

  // ---- statuses ----
  st_created: ['Создан', 'Created'],
  st_pending: ['Ожидает оплаты', 'Awaiting payment'],
  st_processing: ['Обрабатывается', 'Processing'],
  st_paid: ['Оплачено', 'Paid'],
  st_failed: ['Не прошёл', 'Failed'],
  st_expired: ['Истёк', 'Expired'],
  st_cancelled: ['Отменён', 'Cancelled'],
  st_partial: ['Частичный возврат', 'Partly refunded'],
  st_refunded: ['Возвращён', 'Refunded'],
  inv_draft: ['Черновик', 'Draft'],
  inv_pending: ['Ожидает оплаты', 'Awaiting payment'],
  inv_paid: ['Оплачен', 'Paid'],
  inv_expired: ['Просрочен', 'Overdue'],
  inv_cancelled: ['Отменён', 'Cancelled'],
  rf_pending: ['Обрабатывается', 'Processing'],
  rf_completed: ['Возврат выполнен', 'Refunded'],
  rf_failed: ['Не выполнен', 'Failed'],
  src_pos: ['Касса', 'Terminal'],
  src_invoice: ['Счёт', 'Invoice'],
  src_invoice_n: ['Счёт {n}', 'Invoice {n}'],
  src_link: ['Ссылка', 'Link'],

  // ---- app nav ----
  nav_app: ['Разделы', 'Sections'],
  nav_overview: ['Обзор', 'Overview'],
  nav_pos: ['Касса', 'Terminal'],
  nav_transactions: ['Операции', 'Transactions'],
  nav_transactions_short: ['Операции', 'Activity'],
  nav_invoices: ['Счета', 'Invoices'],
  nav_links: ['Ссылки на оплату', 'Payment links'],
  nav_links_short: ['Ссылки', 'Links'],
  nav_settings: ['Настройки', 'Settings'],

  // ---- overview ----
  ov_today: ['Сегодня', 'Today'],
  ov_today_label: ['за сегодня', 'today'],
  ov_received_today: ['Получено сегодня', 'Received today'],
  ov_received_yesterday: ['Получено вчера', 'Received yesterday'],
  ov_yesterday_full: ['за полный день', 'full day'],
  ov_yesterday_label: ['за вчера', 'yesterday'],
  ov_payout_today: ['зачислим сегодня в {when}', 'paid out today at {when}'],
  ov_no_compare: ['вчера в это время платежей не было', 'no payments by this time yesterday'],
  ov_payments: ['Платежей', 'Payments'],
  ov_success: ['{n}% успешных за неделю', '{n}% successful this week'],
  ov_average: ['Средний платёж', 'Average payment'],
  ov_refunds_today: ['возвраты сегодня: {amount}', 'refunded today: {amount}'],
  ov_no_refunds: ['без возвратов сегодня', 'no refunds today'],
  ov_to_settle: ['К выплате', 'To be settled'],
  ov_payout: ['зачислим завтра в {when}', 'paid out tomorrow at {when}'],
  ov_nothing_to_settle: ['сегодня оплат ещё не было', 'no payments yet today'],
  ov_week: ['Выручка за 7 дней', 'Revenue, last 7 days'],
  ov_settlement: ['Выплата', 'Settlement'],
  ov_all_settlements: ['Все выплаты', 'All settlements'],
  ov_no_settlements: ['Выплат пока нет', 'No settlements yet'],
  ov_recent: ['Последние платежи', 'Recent payments'],
  ov_all_transactions: ['Все операции', 'All transactions'],
  ov_mix: ['Чем платят покупатели', 'What customers pay with'],
  ov_30_days: ['30 дней', '30 days'],
  ov_mix_note: ['Вы получаете всё в {asset}: конвертация происходит автоматически.', 'You receive everything in {asset}: conversion is automatic.'],
  ov_no_data: ['Пока нет данных', 'No data yet'],
  ov_invoices_due: ['Счета к оплате', 'Invoices due'],
  ov_open: ['Открыть', 'Open'],
  ov_no_due: ['Все счета оплачены', 'All invoices are paid'],
  ov_settlements_title: ['Выплаты', 'Settlements'],
  ov_settlements_lead: ['Каждый день платежи собираются в одну выплату в {asset}. Деньги приходят на следующий день в 10:00.', 'Each day’s payments are bundled into one {asset} settlement, paid out at 10:00 the next morning.'],

  // ---- settlement ----
  stl_today: ['Сегодня', 'Today'],
  stl_open: ['Собирается', 'Collecting'],
  stl_scheduled: ['Запланирована', 'Scheduled'],
  stl_completed: ['Зачислена', 'Paid out'],
  stl_received: ['Получено в {asset}', 'Received in {asset}'],
  stl_fee: ['Комиссия KVIT, {rate}%', 'KVIT fee, {rate}%'],
  stl_refunds: ['Возвраты', 'Refunds'],
  stl_to_credit: ['К зачислению', 'To be credited'],
  stl_credited: ['Зачислено', 'Credited'],
  stl_payout_at: ['Выплата {when}', 'Payout {when}'],
  stl_paid_at: ['Зачислено {when}', 'Credited {when}'],

  // ---- terminal ----
  pos_sub: ['Введите сумму, покажите QR, получите оплату.', 'Enter an amount, show the QR, get paid.'],
  pos_amount_due: ['Сумма к оплате', 'Amount due'],
  pos_enter_amount: ['Введите сумму с клавиатуры', 'Type the amount'],
  pos_note: ['Комментарий к платежу', 'Payment note'],
  pos_note_ph: ['Комментарий к заказу', 'Order note'],
  pos_keypad: ['Цифровая клавиатура', 'Keypad'],
  pos_backspace: ['Стереть', 'Delete'],
  pos_creating: ['Создаём платёж…', 'Creating payment…'],
  pos_min: ['Минимальная сумма — {amount}', 'Minimum amount is {amount}'],
  pos_keyboard_hint: ['Можно печатать с клавиатуры, Enter — создать', 'You can type on the keyboard, Enter to create'],
  pos_new_session: ['Новый платёж', 'New payment'],
  pos_qr_label: ['QR-код для оплаты', 'Payment QR code'],
  pos_receiving: ['Получаем перевод', 'Receiving transfer'],
  pos_scan_hint: ['Покажите QR покупателю', 'Show the QR to the customer'],
  pos_failed_text: ['Перевод не подтвердился. Покупатель может оплатить ещё раз по этому же QR.', 'The transfer wasn’t confirmed. The customer can pay again with the same QR.'],
  pos_expired_text: ['15 минут на оплату прошли. Создайте платёж заново — сумма сохранится.', 'The 15-minute window has passed. Create it again — the amount is kept.'],
  pos_cancelled_text: ['Платёж отменён, покупатель не сможет его оплатить.', 'The payment was cancelled and can no longer be paid.'],
  pos_open_checkout: ['Открыть экран покупателя', 'Open customer checkout'],
  pos_sim_pay: ['Оплатить', 'Pay'],
  pos_sim_fail: ['Ошибка', 'Fail'],
  pos_sim_expire: ['Истечь', 'Expire'],
  pos_sim_retry: ['Оплатить ещё раз', 'Pay again'],
  pos_cancel: ['Отменить платёж', 'Cancel payment'],
  pos_processing_note: ['Обычно это занимает несколько секунд.', 'This usually takes a few seconds.'],
  pos_details: ['Детали операции', 'Payment details'],
  pos_again: ['Создать заново', 'Create again'],
  pos_not_found: ['Платёж не найден', 'Payment not found'],
  pos_not_found_text: ['Возможно, демо-данные были сброшены.', 'The demo data may have been reset.'],
  pos_today: ['Сегодня на кассе', 'Today at the terminal'],
  pos_today_empty: ['Сегодня оплат на кассе ещё не было', 'No terminal payments yet today'],
  pos_tip_title: ['Как проверить', 'Try it'],
  pos_tip_text: ['Откройте экран покупателя в соседней вкладке и оплатите — статус здесь обновится сам. Или отсканируйте QR телефоном.', 'Open the customer checkout in another tab and pay — the status here updates on its own. Or scan the QR with your phone.'],
  pos_payment: ['Платёж', 'Payment'],
  toast_paid: ['Оплачено: {amount}', 'Paid: {amount}'],

  // ---- checkout ----
  co_doc_title: ['Оплата', 'Payment'],
  co_pay_to: ['Оплата для', 'Payment to'],
  co_method: ['Способ оплаты', 'Payment method'],
  co_wallet: ['Кошелёк', 'Wallet'],
  co_transfer: ['По адресу', 'To address'],
  co_pay_with: ['Чем оплатить', 'Pay with'],
  co_balance: ['баланс', 'balance'],
  co_not_enough: ['не хватает', 'not enough'],
  co_more: ['Ещё {n}', '{n} more'],
  co_less: ['Свернуть', 'Show less'],
  co_amount: ['Сумма', 'Amount'],
  co_network_fee: ['Комиссия сети', 'Network fee'],
  co_total: ['Спишется', 'You pay'],
  co_send_exactly: ['Отправьте ровно', 'Send exactly'],
  co_address: ['Адрес', 'Address'],
  co_pay_btn: ['Оплатить {amount}', 'Pay {amount}'],
  co_sent_btn: ['Я отправил перевод', 'I’ve sent it'],
  co_choose_other: ['Выберите другой актив', 'Choose another asset'],
  co_sandbox_note: ['Кошелёк тестовый, деньги не спишутся.', 'Test wallet, nothing is charged.'],
  co_fail_toggle: ['Симулировать ошибку', 'Simulate a failure'],
  co_processing_title: ['Проверяем перевод', 'Checking the transfer'],
  co_step_found: ['Перевод найден', 'Transfer found'],
  co_step_confirm: ['Подтверждение сети', 'Network confirmation'],
  co_step_credit: ['Зачисление продавцу', 'Crediting the merchant'],
  co_merchant: ['Продавец', 'Merchant'],
  co_when: ['Дата и время', 'Date and time'],
  co_operation: ['Номер операции', 'Payment ID'],
  co_failed_title: ['Платёж не прошёл', 'Payment didn’t go through'],
  co_failed_text: ['Сеть не подтвердила перевод, средства не списаны. Попробуйте ещё раз.', 'The network didn’t confirm the transfer and nothing was charged. Please try again.'],
  co_retry: ['Попробовать снова', 'Try again'],
  co_expired_title: ['Время на оплату истекло', 'This payment has expired'],
  co_expired_text: ['Попросите продавца создать новый платёж.', 'Ask the merchant to create a new payment.'],
  co_closed_title: ['Оплата недоступна', 'Payment unavailable'],
  co_cancelled_text: ['Продавец отменил этот платёж.', 'The merchant cancelled this payment.'],
  co_link_done: ['Эта ссылка уже оплачена и больше не принимает платежи.', 'This link has been paid and no longer accepts payments.'],
  co_link_paused: ['Продавец временно приостановил приём оплаты по этой ссылке.', 'The merchant has paused payments for this link.'],
  co_invoice_expired: ['Срок оплаты счёта истёк. Свяжитесь с продавцом, чтобы получить новый.', 'This invoice is past due. Contact the merchant for a new one.'],
  co_invoice_draft: ['Счёт ещё не выставлен.', 'This invoice hasn’t been issued yet.'],
  co_invoice_cancelled: ['Продавец отменил этот счёт.', 'The merchant cancelled this invoice.'],
  co_back_demo: ['Вернуться в демо', 'Back to the demo'],
  co_powered: ['Платёжная страница', 'Checkout by'],
  co_not_found: ['Платёж не найден', 'Payment not found'],
  co_not_found_text: ['Ссылка устарела или демо-данные были сброшены.', 'The link is out of date or the demo data was reset.'],
  co_page_note: ['Это страница покупателя в демо KVIT.', 'This is the customer page of the KVIT demo.'],
  co_page_note_link: ['Открыть кабинет продавца', 'Open the merchant dashboard'],

  // ---- payment detail ----
  pd_title: ['Операция', 'Payment'],
  pd_not_found: ['Операция не найдена', 'Payment not found'],
  pd_refunded: ['возвращено {amount}', '{amount} refunded'],
  pd_timeline: ['История', 'Timeline'],
  pd_details: ['Детали', 'Details'],
  pd_source: ['Источник', 'Source'],
  pd_customer: ['Покупатель', 'Customer'],
  pd_paid_with: ['Оплачено в', 'Paid with'],
  pd_crypto: ['Получено', 'Received'],
  pd_rate: ['Курс', 'Rate'],
  pd_network_fee: ['Комиссия сети', 'Network fee'],
  pd_fee_by_customer: ['оплатил покупатель', 'paid by customer'],
  pd_from: ['С адреса', 'From'],
  pd_hash: ['Хэш (симуляция)', 'Hash (simulated)'],
  pd_settlement: ['В выплате', 'Settlement'],
  pd_converted: ['Конвертировано в {asset}', 'Converted to {asset}'],
  pd_net: ['Вам начислено', 'Your net'],
  pd_in_settlement: ['Входит в выплату за {date}', 'Part of the {date} settlement'],
  pd_refunds: ['Возвраты', 'Refunds'],
  pd_left: ['Можно вернуть ещё {amount}', '{amount} can still be refunded'],
  pd_open_pos: ['Открыть на кассе', 'Open in terminal'],
  pd_refund_in_progress: ['Возврат обрабатывается', 'Refund in progress'],
  tl_created: ['Платёж создан', 'Payment created'],
  tl_sent: ['Покупатель отправил перевод', 'Customer sent the transfer'],
  tl_paid: ['Оплата подтверждена', 'Payment confirmed'],
  tl_failed: ['Перевод не подтвердился', 'Transfer not confirmed'],
  tl_expired: ['Время на оплату истекло', 'Payment window expired'],
  tl_cancelled: ['Отменён продавцом', 'Cancelled by merchant'],
  tl_refunded: ['Возвращено {amount}', 'Refunded {amount}'],
  tl_refunding: ['Возврат {amount} обрабатывается', 'Refunding {amount}'],
  tl_waiting: ['Ожидаем оплату до {time}', 'Awaiting payment until {time}'],

  // ---- refund ----
  refund_title: ['Возврат платежа', 'Refund payment'],
  rf_original: ['Исходный платёж', 'Original payment'],
  rf_amount: ['Сумма возврата', 'Refund amount'],
  rf_full: ['Полностью, {amount}', 'Full, {amount}'],
  rf_part: ['Частично', 'Partial'],
  rf_max: ['Не больше {max}', 'Up to {max}'],
  rf_err_range: ['Введите сумму от 1 ₽ до {max}', 'Enter an amount from ₽1 to {max}'],
  rf_reason: ['Причина', 'Reason'],
  rf_reason_ph: ['Например, товара нет в наличии', 'E.g. item out of stock'],
  rf_summary: ['Покупатель получит {crypto} на исходный адрес в сети {network}. Сумма будет удержана из ближайшей выплаты. В демо возврат симулирован.', 'The customer receives {crypto} back to the original {network} address. The amount is deducted from your next settlement. Simulated in the demo.'],
  rf_confirm: ['Вернуть {amount}', 'Refund {amount}'],
  rf_failed_toast: ['Не удалось оформить возврат', 'Couldn’t issue the refund'],
  toast_refund_started: ['Возврат {amount} отправлен', 'Refund of {amount} sent'],

  // ---- transactions ----
  tx_sub: ['Все платежи с кассы, по ссылкам и счетам.', 'Every payment from the terminal, links and invoices.'],
  tx_search: ['Поиск', 'Search'],
  tx_search_ph: ['Сумма, описание, покупатель или ID', 'Amount, description, customer or ID'],
  tx_source: ['Источник', 'Source'],
  tx_all_sources: ['Все источники', 'All sources'],
  tx_status_filter: ['Статус', 'Status'],
  f_all: ['Все', 'All'],
  f_paid: ['Оплачены', 'Paid'],
  f_pending: ['Ожидают', 'Pending'],
  f_refunded: ['Возвраты', 'Refunded'],
  f_failed: ['Не прошли', 'Unsuccessful'],
  tx_empty: ['Операций пока нет', 'No payments yet'],
  tx_empty_filter: ['Здесь пока пусто', 'Nothing here yet'],
  tx_nothing: ['По запросу «{q}» ничего нет', 'Nothing matches “{q}”'],
  tx_nothing_hint: ['Попробуйте другой запрос или сбросьте фильтры.', 'Try another search or reset the filters.'],
  tx_reset_filters: ['Сбросить фильтры', 'Reset filters'],
  tx_show_more: ['Показать ещё {n}', 'Show {n} more'],

  // ---- invoices ----
  inv_sub: ['Счета для оптовых клиентов и мероприятий.', 'Invoices for wholesale clients and events.'],
  inv_awaiting: ['Ожидают оплаты', 'Awaiting payment'],
  inv_overdue: ['Просрочены', 'Overdue'],
  inv_paid_30: ['Оплачены за 30 дней', 'Paid, last 30 days'],
  inv_n: ['Счетов: {n}', 'Invoices: {n}'],
  inv_draft_pl: ['Черновики', 'Drafts'],
  inv_pending_pl: ['Ожидают', 'Pending'],
  inv_paid_pl: ['Оплачены', 'Paid'],
  inv_closed_pl: ['Закрыты', 'Closed'],
  inv_col_customer: ['Клиент', 'Customer'],
  inv_col_status: ['Статус', 'Status'],
  inv_due: ['Оплатить до', 'Due'],
  inv_due_on: ['до {date}', 'due {date}'],
  inv_paid_date: ['оплачен {date}', 'paid {date}'],
  inv_sum: ['Сумма', 'Amount'],
  inv_empty: ['Счетов нет', 'No invoices'],
  inv_empty_text: ['Создайте счёт — клиент оплатит его по ссылке.', 'Create an invoice — your client pays it via a link.'],
  inv_new_title: ['Новый счёт', 'New invoice'],
  inv_f_customer: ['Клиент', 'Customer'],
  inv_f_customer_ph: ['Название компании или имя', 'Company or person'],
  inv_f_email: ['Эл. почта', 'Email'],
  inv_f_email_hint: ['Отправим сюда ссылку на оплату', 'We’ll send the payment link here'],
  inv_f_items: ['Позиции', 'Line items'],
  inv_item: ['Наименование', 'Item'],
  inv_qty: ['Кол-во', 'Qty'],
  inv_price: ['Цена', 'Price'],
  inv_f_item_ph: ['Например, эспрессо-смесь, 1 кг', 'E.g. espresso blend, 1 kg'],
  inv_f_remove: ['Удалить позицию', 'Remove item'],
  inv_f_add: ['Добавить позицию', 'Add item'],
  inv_total: ['Итого', 'Total'],
  inv_f_due: ['Срок оплаты', 'Payment terms'],
  inv_days: ['{n} дн.', '{n} days'],
  inv_f_memo: ['Комментарий для клиента', 'Note to customer'],
  inv_f_memo_ph: ['Например, условия доставки', 'E.g. delivery details'],
  inv_save_draft: ['Сохранить черновик', 'Save draft'],
  inv_send: ['Создать и отправить', 'Create and send'],
  inv_preview: ['Так клиент увидит счёт', 'What your client will see'],
  inv_doc_title: ['Счёт', 'Invoice'],
  inv_doc_label: ['Счёт {n}', 'Invoice {n}'],
  inv_bill_to: ['Кому', 'Bill to'],
  inv_issued: ['Выставлен', 'Issued'],
  inv_paid_on: ['Оплачен', 'Paid'],
  inv_doc_foot: ['Оплата криптовалютой через KVIT: USDT, USDC, TON, BTC или ETH.', 'Pay with crypto via KVIT: USDT, USDC, TON, BTC or ETH.'],
  inv_not_found: ['Счёт не найден', 'Invoice not found'],
  inv_send_now: ['Отправить счёт', 'Send invoice'],
  inv_open_payment: ['Открыть платёж', 'View payment'],
  inv_reissue: ['Выставить заново', 'Reissue'],
  inv_share: ['Ссылка на оплату', 'Payment link'],
  inv_share_text: ['Клиент получил её на почту. Можно переслать и вручную.', 'Your client got it by email. You can also share it yourself.'],
  inv_tl_created: ['Счёт создан', 'Invoice created'],
  inv_tl_sent: ['Отправлен на {email}', 'Sent to {email}'],
  inv_tl_waiting: ['Ожидаем оплату', 'Awaiting payment'],
  inv_tl_paid: ['Оплачен', 'Paid'],
  inv_tl_expired: ['Срок оплаты истёк', 'Became overdue'],
  inv_tl_cancelled: ['Отменён', 'Cancelled'],
  inv_until: ['до {date}', 'until {date}'],
  inv_cancel: ['Отменить счёт', 'Cancel invoice'],
  inv_cancel_title: ['Отменить счёт {n}?', 'Cancel invoice {n}?'],
  inv_cancel_text: ['Клиент больше не сможет оплатить его по ссылке. Счёт останется в истории.', 'Your client won’t be able to pay it anymore. The invoice stays in your history.'],
  inv_keep: ['Не отменять', 'Keep invoice'],
  inv_cancel_confirm: ['Отменить счёт', 'Cancel invoice'],
  toast_invoice_sent: ['Счёт отправлен на {email}', 'Invoice sent to {email}'],
  toast_invoice_draft: ['Черновик сохранён', 'Draft saved'],
  toast_invoice_cancelled: ['Счёт отменён', 'Invoice cancelled'],
  err_required: ['Заполните поле', 'Required'],
  err_email: ['Проверьте адрес почты', 'Check the email address'],
  err_items: ['У каждой позиции должны быть название, количество и цена', 'Every item needs a name, quantity and price'],
  err_total: ['Сумма в демо — не больше 10 млн ₽', 'The demo limit is ₽10M'],
  err_min_amount: ['Минимальная сумма — {amount}', 'Minimum amount is {amount}'],

  // ---- links ----
  lnk_sub: ['Одна ссылка — для сайта, соцсетей или сообщения клиенту.', 'One link for your site, socials or a message to a customer.'],
  lnk_active: ['Активна', 'Active'],
  lnk_paused: ['Приостановлена', 'Paused'],
  lnk_completed: ['Оплачена', 'Paid'],
  lnk_reusable: ['Многоразовая', 'Reusable'],
  lnk_oneoff: ['Одноразовая', 'One-time'],
  lnk_stats: ['Оплат: {n} · {total}', 'Paid: {n} · {total}'],
  lnk_no_payments: ['Оплат пока нет', 'No payments yet'],
  lnk_no_payments_text: ['Отправьте ссылку покупателю или откройте страницу оплаты сами.', 'Send the link to a customer or open the payment page yourself.'],
  lnk_empty: ['Ссылок пока нет', 'No links yet'],
  lnk_empty_text: ['Создайте ссылку — её можно отправить в сообщении или поставить на сайт.', 'Create a link to send in a message or put on your site.'],
  lnk_not_found: ['Ссылка не найдена', 'Link not found'],
  lnk_share: ['Ссылка и QR', 'Link and QR'],
  lnk_share_text: ['Покупатель откроет страницу, выберет чем платить и оплатит.', 'Customers open the page, choose how to pay and pay.'],
  lnk_paused_text: ['Сейчас по ссылке нельзя оплатить. Включите приём, когда будете готовы.', 'Payments are paused. Turn them back on when you’re ready.'],
  lnk_completed_text: ['Одноразовая ссылка уже оплачена и закрыта.', 'This one-time link has been paid and is closed.'],
  lnk_accepting: ['Принимает оплату', 'Accepting payments'],
  lnk_payments: ['Оплаты по ссылке', 'Payments via this link'],
  lnk_page: ['Страница оплаты', 'Payment page'],
  lnk_paid_count: ['Оплат', 'Paid'],
  lnk_last: ['Последняя оплата', 'Last payment'],
  lnk_f_title: ['Название', 'Title'],
  lnk_f_title_hint: ['Покупатель увидит его на странице оплаты', 'Customers see this on the payment page'],
  lnk_f_title_ph: ['Например, Кения АА, 250 г', 'E.g. Kenya AA, 250 g'],
  lnk_f_desc: ['Описание', 'Description'],
  lnk_f_desc_ph: ['Что входит, сроки доставки', 'What’s included, delivery time'],
  lnk_f_amount: ['Сумма', 'Amount'],
  lnk_reusable_text: ['Оплатить можно сколько угодно раз — подходит для товаров и услуг.', 'Can be paid any number of times — for products and services.'],
  lnk_oneoff_text: ['Закроется после первой оплаты — подходит для предоплат.', 'Closes after the first payment — good for deposits.'],
  lnk_f_note: ['Покупатель сам выберет актив и сеть, вы получите выплату в USDT.', 'Customers pick the asset and network; you are settled in USDT.'],
  lnk_create_btn: ['Создать ссылку', 'Create link'],
  toast_link_created: ['Ссылка создана', 'Link created'],
  toast_link_on: ['Приём оплаты включён', 'Payments resumed'],
  toast_link_off: ['Приём оплаты приостановлен', 'Payments paused'],

  // ---- settings ----
  set_sub: ['Профиль, выплаты и способы оплаты.', 'Profile, payouts and payment methods.'],
  set_business: ['Компания', 'Business'],
  set_name: ['Название для покупателей', 'Public name'],
  set_name_hint: ['Показывается на странице оплаты и в счетах', 'Shown on checkout pages and invoices'],
  set_settlement: ['Выплаты', 'Settlements'],
  set_settle_asset: ['Валюта выплат', 'Settlement currency'],
  set_settle_asset_hint: ['Все платежи конвертируются в неё', 'Every payment is converted to it'],
  set_wallet: ['Кошелёк для выплат', 'Payout wallet'],
  set_wallet_hint: ['Сеть TON', 'TON network'],
  set_schedule: ['График', 'Schedule'],
  set_schedule_hint: ['Платежи за день — одной выплатой', 'One payout per day of payments'],
  set_schedule_v: ['Ежедневно, 10:00', 'Daily, 10:00'],
  set_fee: ['Комиссия', 'Fee'],
  set_fee_hint: ['Удерживается из выплаты, покупатель её не видит', 'Deducted from the payout, not shown to customers'],
  set_assets: ['Способы оплаты', 'Payment methods'],
  set_assets_lead: ['Что покупатель увидит на странице оплаты.', 'What customers can choose at checkout.'],
  set_need_one: ['Оставьте хотя бы один способ оплаты', 'Keep at least one payment method'],
  set_language: ['Язык', 'Language'],
  set_language_k: ['Язык интерфейса', 'Interface language'],
  set_language_hint: ['Запоминается в этом браузере', 'Remembered in this browser'],
  set_developers: ['Для разработчиков', 'Developers'],
  set_api_key: ['Ключ API', 'API key'],
  set_api_key_hint: ['Тестовый ключ песочницы', 'Sandbox test key'],
  set_show: ['Показать', 'Show'],
  set_hide: ['Скрыть', 'Hide'],
  set_rotate: ['Выпустить новый', 'Roll key'],
  set_rotate_title: ['Выпустить новый ключ?', 'Roll the API key?'],
  set_rotate_text: ['Текущий тестовый ключ перестанет работать.', 'The current test key will stop working.'],
  set_webhooks: ['Вебхуки', 'Webhooks'],
  set_webhooks_hint: ['Уведомления о платежах на ваш сервер', 'Payment events sent to your server'],
  set_demo: ['Демо-данные', 'Demo data'],
  set_reset: ['Начать заново', 'Start over'],
  set_reset_hint: ['Вернуть исходные платежи, счета и ссылки', 'Restore the original payments, invoices and links'],
  set_reset_btn: ['Сбросить демо', 'Reset demo'],
  set_reset_title: ['Сбросить демо-данные?', 'Reset demo data?'],
  set_reset_text: ['Созданные вами платежи, счета и ссылки удалятся, вернутся исходные данные.', 'Payments, invoices and links you created will be removed and the original data restored.'],
  toast_saved: ['Сохранено', 'Saved'],
  toast_reset: ['Демо-данные сброшены', 'Demo data reset'],
  toast_key_rotated: ['Новый ключ выпущен', 'New key issued'],

  // ---- site ----
  site_title: ['KVIT — приём криптовалюты для бизнеса', 'KVIT — crypto payments for merchants'],
  skip: ['К содержанию', 'Skip to content'],
  nav_site: ['Разделы сайта', 'Site sections'],
  sn_product: ['Продукт', 'Product'],
  sn_payments: ['Оплата', 'Payments'],
  sn_invoices: ['Счета', 'Invoices'],
  sn_dashboard: ['Кабинет', 'Dashboard'],
  hero_eyebrow: ['Платежи в криптовалюте для бизнеса', 'Crypto payments for merchants'],
  hero_title: ['Принимайте крипту. Без лишней сложности.', 'Accept crypto. Keep it simple.'],
  hero_sub: ['Касса, ссылки на оплату, счета и кабинет с выплатами — в одном понятном интерфейсе.', 'POS, payment links, invoices and a merchant dashboard in one clear workflow.'],
  hero_fact_rate: ['Курс сейчас', 'Rate now'],
  hero_fact_time: ['Оплата', 'Payment'],
  hero_fact_time_v: ['за секунды', 'in seconds'],
  hero_fact_payout: ['Выплата', 'Payout'],
  hero_fact_payout_v: ['раз в день в USDT', 'daily, in USDT'],
  hero_live: ['онлайн', 'live'],
  hero_stage_label: ['Пример: платёж на кассе', 'Example: a payment at the terminal'],
  how_eyebrow: ['Как это работает', 'How it works'],
  how_title: ['Платёж за три шага', 'A payment in three steps'],
  how_lead: ['Продавцу не нужно разбираться в сетях и токенах. Он видит сумму в рублях и статус.', 'Merchants don’t need to know about networks or tokens. They see an amount and a status.'],
  how_1_t: ['Введите сумму', 'Enter the amount'],
  how_1_p: ['В рублях, как на обычном терминале. KVIT сам пересчитает её по текущему курсу.', 'In your own currency, like any terminal. KVIT converts it at the current rate.'],
  how_2_t: ['Покупатель платит', 'The customer pays'],
  how_2_p: ['Сканирует QR, выбирает чем платить и видит итоговую сумму с комиссией сети.', 'They scan the QR, choose how to pay and see the total including the network fee.'],
  how_3_t: ['Оплата видна сразу', 'You see it immediately'],
  how_3_p: ['Статус на кассе меняется за секунды. Вечером всё приходит одной выплатой.', 'The terminal updates within seconds. Everything is settled in one daily payout.'],
  co_eyebrow: ['Экран оплаты', 'Checkout'],
  co_title: ['Понятно даже тем, кто платит криптой впервые', 'Clear even for a first-time crypto payer'],
  co_lead: ['Сумма, продавец и одна кнопка. Сети и комиссии появляются только там, где без них нельзя.', 'An amount, a merchant and one button. Networks and fees show up only where they matter.'],
  co_p1_t: ['Итог без сюрпризов.', 'No surprise totals.'],
  co_p1_p: ['Комиссия сети показана до оплаты, курс — рядом.', 'The network fee is shown before paying, with the rate next to it.'],
  co_p2_t: ['Подсказки вместо ошибок.', 'Guidance instead of errors.'],
  co_p2_p: ['Если на балансе не хватает, страница предложит другой актив.', 'If a balance is short, the page suggests another asset.'],
  co_p3_t: ['Кошелёк или перевод.', 'Wallet or transfer.'],
  co_p3_p: ['Оплата в один шаг или по адресу и QR для любого кошелька.', 'One-tap payment, or an address and QR for any wallet.'],
  co_try_note: ['Это рабочий экран: выберите актив и оплатите. Можно включить ошибку и посмотреть, что увидит покупатель.', 'This screen works: pick an asset and pay. You can also simulate a failure to see what the customer sees.'],
  co_try_again: ['Пройти ещё раз', 'Try again'],
  li_eyebrow: ['Ссылки и счета', 'Links and invoices'],
  li_title: ['Когда покупатель не стоит у кассы', 'When the customer isn’t at the counter'],
  li_lead: ['Продажи в мессенджере, предоплата за мероприятие, опт для кофеен — всё оплачивается по ссылке.', 'Sales in chat, event deposits, wholesale orders — all paid via a link.'],
  li_link_t: ['Ссылка на оплату', 'Payment link'],
  li_link_p: ['Создаётся за полминуты. Многоразовая — для товара на сайте, одноразовая — для предоплаты.', 'Ready in half a minute. Reusable for a product page, one-time for a deposit.'],
  li_link_cta: ['Создать ссылку в демо', 'Create a link in the demo'],
  li_inv_t: ['Счёт для клиента', 'Invoice'],
  li_inv_p: ['Позиции, срок оплаты и статус. Клиент получает ссылку на почту, а вы видите, когда счёт оплачен или просрочен.', 'Line items, terms and status. Your client gets a link by email; you see when it’s paid or overdue.'],
  li_inv_cta: ['Выставить счёт в демо', 'Create an invoice in the demo'],
  db_eyebrow: ['03 — Кабинет', '03 — Dashboard'],
  db_title: ['Сколько пришло —|видно сразу.', 'See what came in|at a glance.'],
  db_lead: ['Выручка, число платежей, средний чек и ближайшая выплата. График — чтобы сравнить дни, не для красоты.', 'Revenue, payments, average ticket and your next payout. The chart compares days — it isn’t decoration.'],
  db_note: ['Это данные из демо. Создайте платёж — цифры здесь изменятся.', 'This is live demo data. Create a payment and these numbers will change.'],
  rs_eyebrow: ['04 — Выплаты и возвраты', '04 — Payouts and refunds'],
  rs_title: ['Одна выплата в день.|Возврат — в два клика.', 'One payout a day.|Refunds in two clicks.'],
  rs_lead: ['Покупатель платит в любом активе — вы получаете одну выплату в USDT с расшифровкой.', 'Customers pay in any asset; you get one USDT payout with a full breakdown.'],
  rs_refund_t: ['Как выглядит возврат', 'What a refund looks like'],
  rs_refund_p: ['Полный или частичный. Деньги возвращаются на исходный адрес, сумма удерживается из выплаты.', 'Full or partial. Funds go back to the original address and are deducted from your payout.'],
  rs_returned: ['Вернули покупателю', 'Returned to customer'],
  rs_tl_1: ['Продавец оформил возврат', 'Merchant issued a refund'],
  rs_tl_2: ['Перевод отправлен в сети {network}', 'Transfer sent on {network}'],
  rs_tl_3: ['Удержано из выплаты', 'Deducted from settlement'],
  rs_refund_cta: ['Посмотреть возвраты в демо', 'See refunds in the demo'],
  rs_settle_t: ['Расшифровка выплаты', 'Payout breakdown'],
  rs_settle_p: ['Сколько заплатили покупатели, сколько получено в {asset}, комиссия, возвраты и итог к зачислению.', 'What customers paid, what was received in {asset}, fees, refunds and the net amount.'],
  rs_settle_cta: ['Открыть выплаты в демо', 'Open settlements in the demo'],
  cta_title: ['Пройдите весь путь платежа за минуту', 'Walk through a full payment in a minute'],
  cta_text: ['Всё работает в браузере: настоящие экраны, ненастоящие деньги.', 'It all runs in your browser: real screens, simulated money.'],
  cta_btn: ['Принять первый платёж', 'Take your first payment'],
  cta_btn_2: ['Открыть кабинет', 'Open dashboard'],
  foot_text: ['KVIT — концепт продукта. Платежи, балансы и выплаты в демо симулированы, курсы — реальные, CoinGecko.', 'KVIT is a product concept. Payments, balances and payouts in the demo are simulated; rates are real, from CoinGecko.'],
  foot_portfolio: ['Портфолио KERNØ', 'KERNØ portfolio'],

  // ---- redesign: site ----
  hero_cta_2: ['Как это работает', 'See how it works'],
  proof_1_v: ['~5 с', '~5 s'],
  proof_1_l: ['до статуса «Оплачено»', 'until it says Paid'],
  proof_2_v: ['6', '6'],
  proof_2_l: ['активов и сетей на выбор', 'assets and networks'],
  proof_3_v: ['1×', '1×'],
  proof_3_l: ['выплата в день, в USDT', 'payout a day, in USDT'],
  ph_amount: ['Сумма', 'Amount'],
  ph_pay: ['Оплата', 'Paying'],
  ph_paid: ['Оплачено', 'Paid'],
  s1_eyebrow: ['01 — Касса', '01 — Terminal'],
  s1_title: ['Создайте платёж.|Покажите QR.|Готово.', 'Create payment.|Show QR.|Done.'],
  s1_lead: ['Продавец работает с суммой в рублях. Сети, токены и курсы KVIT берёт на себя.', 'Merchants work with an amount in their currency. KVIT handles networks, tokens and rates.'],
  s1_1_t: ['Введите сумму', 'Enter the amount'],
  s1_1_p: ['Как на обычном терминале. Можно добавить комментарий к заказу.', 'Like any card terminal. Add an order note if you like.'],
  s1_2_t: ['Покажите QR', 'Show the QR'],
  s1_2_p: ['Код действует 15 минут, курс фиксируется в момент оплаты.', 'The code is valid for 15 minutes; the rate locks when the customer pays.'],
  s1_3_t: ['Покупатель платит', 'The customer pays'],
  s1_3_p: ['Выбирает USDT, TON или BTC и видит итог вместе с комиссией сети.', 'They pick USDT, TON or BTC and see the total including the network fee.'],
  s1_4_t: ['Оплачено', 'Paid'],
  s1_4_p: ['Статус на кассе меняется за секунды. Деньги уходят в ежедневную выплату.', 'The terminal updates in seconds. The money joins your daily payout.'],
  s1_cta: ['Принять платёж в демо', 'Take a payment in the demo'],
  frame_merchant: ['Касса · продавец', 'Terminal · merchant'],
  frame_customer: ['Телефон · покупатель', 'Phone · customer'],
  try_eyebrow: ['Экран оплаты', 'Checkout'],
  try_title: ['Оплатите сами', 'Pay it yourself'],
  try_lead: ['Это настоящий экран покупателя. Выберите актив и нажмите «Оплатить» — деньги ненастоящие.', 'This is the real customer screen. Pick an asset and press Pay — the money is simulated.'],
  try_tag: ['Работает — попробуйте', 'Live — try it'],
  s2_eyebrow: ['02 — Счета и ссылки', '02 — Invoices and links'],
  s2_title: ['Выставьте счёт.|Отправьте ссылку.|Получите оплату.', 'Send an invoice.|Share a link.|Get paid.'],
  s2_lead: ['Для опта, предзаказов и продаж в мессенджерах — когда покупатель не стоит у кассы.', 'For wholesale, pre-orders and chat sales — when the customer isn’t at the counter.'],
  s2_1_t: ['Счёт с позициями', 'An itemised invoice'],
  s2_1_p: ['Клиент, позиции, срок оплаты. Итог KVIT посчитает сам.', 'Customer, items and terms. KVIT adds up the total.'],
  s2_2_t: ['Ссылка уходит клиенту', 'The link goes out'],
  s2_2_p: ['На почту или в мессенджер. Та же ссылка работает как QR.', 'By email or chat. The same link works as a QR.'],
  s2_3_t: ['Клиент оплачивает', 'The client pays'],
  s2_3_p: ['Видит позиции и сумму, платит с любого кошелька.', 'They see the items and total and pay from any wallet.'],
  s2_4_t: ['Деньги в кабинете', 'It lands in your dashboard'],
  s2_4_p: ['Счёт отмечается оплаченным, сумма попадает в выручку дня.', 'The invoice is marked paid and the amount joins the day’s revenue.'],
  s2_cta: ['Выставить счёт в демо', 'Create an invoice in the demo'],
  s2_cta2: ['Создать ссылку', 'Create a link'],
  frame_link_title: ['Ссылка на оплату', 'Payment link'],
  frame_sent: ['Отправлено на {email}', 'Sent to {email}'],
  frame_plus: ['+{amount} по счёту KC-0146', '+{amount} from invoice KC-0146'],
  cta_a1: ['Принять платёж на кассе', 'Take a payment at the terminal'],
  cta_a1_s: ['Сумма, QR, статус «Оплачено»', 'Amount, QR, Paid'],
  cta_a2: ['Выставить счёт', 'Send an invoice'],
  cta_a2_s: ['Позиции, срок, ссылка на оплату', 'Items, terms, payment link'],
  cta_a3: ['Создать ссылку на оплату', 'Create a payment link'],
  cta_a3_s: ['Для сайта и мессенджеров', 'For your site and chats'],

  // ---- redesign: links ----
  pay_forms: ['оплата|оплаты|оплат', 'payment|payments'],
  lnk_sum_received: ['Получено по ссылкам', 'Received via links'],
  lnk_sum_payments: ['Оплат по ссылкам', 'Link payments'],
  lnk_sum_active: ['Активных ссылок', 'Active links'],
  lnk_sum_30: ['за 30 дней', 'last 30 days'],
  lnk_sum_total: ['из {n}', 'of {n}'],
  lnk_details: ['Ссылка на оплату', 'Payment link'],
  lnk_received: ['{total} получено', '{total} received'],
  lnk_open: ['Открыть', 'Open'],
  lnk_share_btn: ['Поделиться', 'Share'],
  lnk_resume: ['Возобновить', 'Resume'],
  lnk_paid_on: ['Оплачена {date}', 'Paid {date}'],
  lnk_customer_sees: ['Так видит покупатель', 'What the customer sees'],
  lnk_preview_pay: ['Оплатить', 'Pay'],
  lnk_revenue: ['Получено', 'Received'],
  lnk_status: ['Статус', 'Status'],
  lnk_created: ['Создана', 'Created'],
  toast_link_copied: ['Ссылка скопирована', 'Link copied'],
} as const satisfies Record<string, readonly [string, string]>;

export type Key = keyof typeof dict;
